name: Release Forkgram AppImages
permissions:
  contents: write
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 11 * * 0-6"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      forkgram_version: ${{ steps.set_version.outputs.forkgram_version }}
    steps:
      - uses: actions/checkout@v3

      - name: build
        run: bash build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: forkgram.AppImage
          path: |
            forkgram.AppImage*

      - id: set_version
        run: echo "forkgram_version=$FORKGRAM_VERSION" >> $GITHUB_OUTPUT

  release:
    if: github.event.repository.fork == false || secrets.RELEASE_TOKEN != ''
    needs: [build]
    runs-on: ubuntu-latest
    env:
      GH_RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN != '' && secrets.RELEASE_TOKEN || secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/download-artifact@v4.1.8
        with:
          name: forkgram.AppImage
          path: .

      # Snapshot Release
      - name: get date
        run: |
          SNAPSHOT_TAG="$(date --utc +'%Y%m%d-%H%M%S')"
          echo SNAPSHOT_TAG="${SNAPSHOT_TAG}" >> "${GITHUB_ENV}"
        continue-on-error: false
      - name: create snapshot
        uses: softprops/action-gh-release@v2
        with:
          name: "Snapshot ${{ needs.build.outputs.forkgram_version }}"
          tag_name: "${{ env.SNAPSHOT_TAG }}"
          prerelease: false
          draft: false
          generate_release_notes: false
          make_latest: false
          files: |
            *.AppImage*
          token: ${{ env.GH_RELEASE_TOKEN }}
        continue-on-error: false

      # Continuous releases
      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Continuous builds
          automatic_release_tag: continuous
          prerelease: false
          draft: false
          files: |
            *.AppImage*
          repo_token: ${{ env.GH_RELEASE_TOKEN }}
